spring.application.name=TheDeckForge
spring.datasource.url=jdbc:mysql://localhost:3306/TheDeckForge
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.web.resources.static-locations=classpath:/static/
spring.mvc.contentnegotiation.media-types.webp=image/webp

spring.sql.init.mode=always
spring.sql.init.separator=;

spring.thymeleaf.cache=false

server.port=8080