-- =============================================================
-- DeckforgeDB — generated by scripts/generate_card_data.py
-- Real MTG card data from Scryfall API
-- =============================================================

-- --------------------------------------------------------
-- Card_Register (25 real MTG cards from Scryfall)
-- --------------------------------------------------------
INSERT INTO Cards
    (CharacterName, CardType, Color, CardSet, Rarity, RuleText, PictureReference, ManaCost, ATK, DEF)
VALUES
    ('Tempest Djinn', 'Creature', 'Blue', 'Foundations', 'Rare', 'Flying This creature gets +1/+0 for each basic Island you control.', '/img/cards/tempest_djinn.jpg', '{U}{U}{U}', 0, 4),
    ('Steel Overseer', 'Creature', 'Gray', 'Edge of Eternities Commander', 'Rare', '{T}: Put a +1/+1 counter on each artifact creature you control.', '/img/cards/steel_overseer.jpg', '{2}', 1, 1),
    ('Ember Hauler', 'Creature', 'Red', 'Core Set 2020', 'Uncommon', '{1}, Sacrifice this creature: It deals 2 damage to any target.', '/img/cards/ember_hauler.jpg', '{R}{R}', 2, 2),
    ('Wall of Roots', 'Creature', 'Green', 'Tarkir: Dragonstorm Commander', 'Common', 'Defender Put a -0/-1 counter on this creature: Add {G}. Activate only once each turn.', '/img/cards/wall_of_roots.jpg', '{1}{G}', 0, 5),
    ('Royal Assassin', 'Creature', 'Black', 'Dominaria Remastered', 'Rare', '{T}: Destroy target tapped creature.', '/img/cards/royal_assassin.jpg', '{1}{B}{B}', 1, 1),
    ('Knight of the Reliquary', 'Creature', 'Green,White', 'Iconic Masters', 'Rare', 'This creature gets +1/+1 for each land card in your graveyard. {T}, Sacrifice a Forest or Plains: Search your library for a land card, put it onto the battlefield, then shuffle.', '/img/cards/knight_of_the_reliquary.jpg', '{1}{G}{W}', 2, 2),
    ('Counterspell', 'Instant', 'Blue', 'Duskmourn: House of Horror Commander', 'Uncommon', 'Counter target spell.', '/img/cards/counterspell.jpg', '{U}{U}', NULL, 0),
    ('Pyroclasm', 'Sorcery', 'Red', 'Duskmourn: House of Horror', 'Uncommon', 'Pyroclasm deals 2 damage to each creature.', '/img/cards/pyroclasm.jpg', '{1}{R}', NULL, 0),
    ('Harmonize', 'Sorcery', 'Green', 'Teenage Mutant Ninja Turtles Eternal', 'Uncommon', 'Draw three cards.', '/img/cards/harmonize.jpg', '{2}{G}{G}', NULL, 0),
    ('Cursed Scroll', 'Artifact', 'Gray', 'Tempest Remastered', 'Mythic', '{3}, {T}: Choose a card name, then reveal a card at random from your hand. If that card has the chosen name, this artifact deals 2 damage to any target.', '/img/cards/cursed_scroll.jpg', '{1}', NULL, 0),
    ('Rekindling Phoenix', 'Creature', 'Red', 'New Capenna Commander', 'Mythic', 'Flying When this creature dies, create a 0/1 red Elemental creature token with "At the beginning of your upkeep, sacrifice this token and return target card named Rekindling Phoenix from your graveyard to the battlefield. It gains haste until end of turn."', '/img/cards/rekindling_phoenix.jpg', '{2}{R}{R}', 4, 3),
    ('Soldier of the Pantheon', 'Creature', 'White', 'Theros', 'Rare', 'Protection from multicolored Whenever an opponent casts a multicolored spell, you gain 1 life.', '/img/cards/soldier_of_the_pantheon.jpg', '{W}', 2, 1),
    ('Soul Warden', 'Creature', 'White', 'Modern Masters 2017', 'Common', 'Whenever another creature enters, you gain 1 life.', '/img/cards/soul_warden.jpg', '{W}', 1, 1),
    ('Path to Exile', 'Instant', 'White', 'Secrets of Strixhaven Commander', 'Uncommon', 'Exile target creature. Its controller may searchTerm their library for a basic land card, put that card onto the battlefield tapped, then shuffle.', '/img/cards/path_to_exile.jpg', '{W}', NULL, 0),
    ('Cloud Sprite', 'Creature', 'Blue', 'Tenth Edition', 'Common', 'Flying (This creature can''t be blocked except by creatures with flying or reach.) This creature can block only creatures with flying.', '/img/cards/cloud_sprite.jpg', '{U}', 1, 1),
    ('Looter il-Kor', 'Creature', 'Blue', 'Commander Masters', 'Common', 'Shadow (This creature can block or be blocked by only creatures with shadow.) Whenever this creature deals damage to an opponent, draw a card, then discard a card.', '/img/cards/looter_il-kor.jpg', '{1}{U}', 1, 1),
    ('Telling Time', 'Instant', 'Blue', 'Duskmourn: House of Horror Commander', 'Uncommon', 'Look at the top three cards of your library. Put one of those cards into your hand, one on top of your library, and one on the bottom of your library.', '/img/cards/telling_time.jpg', '{1}{U}', NULL, 0),
    ('Gravecrawler', 'Creature', 'Black', 'Tarkir: Dragonstorm Commander', 'Rare', 'This creature can''t block. You may cast this card from your graveyard as long as you control a Zombie.', '/img/cards/gravecrawler.jpg', '{B}', 2, 1),
    ('Vampire Nighthawk', 'Creature', 'Black', 'Foundations', 'Uncommon', 'Flying Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.) Lifelink (Damage dealt by this creature also causes you to gain that much life.)', '/img/cards/vampire_nighthawk.jpg', '{1}{B}{B}', 2, 3),
    ('Sign in Blood', 'Sorcery', 'Black', 'Duskmourn: House of Horror Commander', 'Common', 'Target player draws two cards and loses 2 life.', '/img/cards/sign_in_blood.jpg', '{B}{B}', NULL, 0),
    ('Goblin Guide', 'Creature', 'Red', 'Double Masters', 'Rare', 'Haste Whenever this creature attacks, defending player reveals the top card of their library. If it''s a land card, that player puts it into their hand.', '/img/cards/goblin_guide.jpg', '{R}', 2, 2),
    ('Young Pyromancer', 'Creature', 'Red', 'Tarkir: Dragonstorm Commander', 'Uncommon', 'Whenever you cast an instant or sorcery spell, create a 1/1 red Elemental creature token.', '/img/cards/young_pyromancer.jpg', '{1}{R}', 2, 1),
    ('Rampaging Brontodon', 'Creature', 'Green', 'The Lost Caverns of Ixalan Commander', 'Rare', 'Trample Whenever this creature attacks, it gets +1/+1 until end of turn for each land you control.', '/img/cards/rampaging_brontodon.jpg', '{5}{G}{G}', 7, 7),
    ('Primalcrux', 'Creature', 'Green', 'Eventide', 'Rare', 'Trample Chroma — This creature''s power and toughness are each equal to the number of green mana symbols in the mana costs of permanents you control.', '/img/cards/primalcrux.jpg', '{G}{G}{G}{G}{G}{G}', NULL, 0),
    ('Command Tower', 'Land', 'Gray', 'Secrets of Strixhaven Commander', 'Common', '{T}: Add one mana of any color in your commander''s color identity.', '/img/cards/command_tower.jpg', '', NULL, 0),
    ('Serra Angel', 'Creature', 'White', 'Foundations', 'Uncommon', 'Flying Vigilance (Attacking doesn''t cause this creature to tap.)', '/img/cards/serra_angel.jpg', '{3}{W}{W}', 4, 4),
    ('Wrath of God', 'Sorcery', 'White', 'Commander Masters', 'Rare', 'Destroy all creatures. They can''t be regenerated.', '/img/cards/wrath_of_god.jpg', '{2}{W}{W}', NULL, 0),
    ('Swords to Plowshares', 'Instant', 'White', 'Secrets of Strixhaven Commander', 'Uncommon', 'Exile target creature. Its controller gains life equal to its power.', '/img/cards/swords_to_plowshares.jpg', '{W}', NULL, 0),
    ('Ajani''s Pridemate', 'Creature', 'White', 'Foundations', 'Uncommon', 'Whenever you gain life, put a +1/+1 counter on this creature.', '/img/cards/ajanis_pridemate.jpg', '{1}{W}', 2, 2),
    ('Mother of Runes', 'Creature', 'White', 'Commander Legends: Battle for Baldur''s Gate', 'Uncommon', '{T}: Target creature you control gains protection from the color of your choice until end of turn.', '/img/cards/mother_of_runes.jpg', '{W}', 1, 1),
    ('Stoneforge Mystic', 'Creature', 'White', 'Double Masters', 'Rare', 'When this creature enters, you may searchTerm your library for an Equipment card, reveal it, put it into your hand, then shuffle. {1}{W}, {T}: You may put an Equipment card from your hand onto the battlefield.', '/img/cards/stoneforge_mystic.jpg', '{1}{W}', 1, 2),
    ('Thalia, Guardian of Thraben', 'Creature', 'White', 'Innistrad: Crimson Vow', 'Rare', 'First strike Noncreature spells cost {1} more to cast.', '/img/cards/thalia_guardian_of_thraben.jpg', '{1}{W}', 2, 1),
    ('Sun Titan', 'Creature', 'White', 'Secrets of Strixhaven Commander', 'Mythic', 'Vigilance Whenever this creature enters or attacks, you may return target permanent card with mana value 3 or less from your graveyard to the battlefield.', '/img/cards/sun_titan.jpg', '{4}{W}{W}', 6, 6),
    ('Brave the Elements', 'Instant', 'White', 'Commander 2014', 'Uncommon', 'Choose a color. White creatures you control gain protection from the chosen color until end of turn.', '/img/cards/brave_the_elements.jpg', '{W}', NULL, 0),
    ('Land Tax', 'Enchantment', 'White', 'Secrets of Strixhaven Commander', 'Mythic', 'At the beginning of your upkeep, if an opponent controls more lands than you, you may searchTerm your library for up to three basic land cards, reveal them, put them into your hand, then shuffle.', '/img/cards/land_tax.jpg', '{W}', NULL, 0),
    ('Spectral Procession', 'Sorcery', 'White', 'Modern Masters 2015', 'Uncommon', 'Create three 1/1 white Spirit creature tokens with flying.', '/img/cards/spectral_procession.jpg', '{2/W}{2/W}{2/W}', NULL, 0),
    ('Elspeth, Knight-Errant', 'Planeswalker', 'White', 'Modern Masters', 'Mythic', '+1: Create a 1/1 white Soldier creature token. +1: Target creature gets +3/+3 and gains flying until end of turn. −8: You get an emblem with "Artifacts, creatures, enchantments, and lands you control have indestructible."', '/img/cards/elspeth_knight-errant.jpg', '{2}{W}{W}', NULL, 0),
    ('Brainstorm', 'Instant', 'Blue', 'Duskmourn: House of Horror Commander', 'Common', 'Draw three cards, then put two cards from your hand on top of your library in any order.', '/img/cards/brainstorm.jpg', '{U}', NULL, 0),
    ('Force of Will', 'Instant', 'Blue', 'Dominaria Remastered', 'Mythic', 'You may pay 1 life and exile a blue card from your hand rather than pay this spell''s mana cost. Counter target spell.', '/img/cards/force_of_will.jpg', '{3}{U}{U}', NULL, 0),
    ('Snapcaster Mage', 'Creature', 'Blue', 'Innistrad Remastered', 'Mythic', 'Flash When this creature enters, target instant or sorcery card in your graveyard gains flashback until end of turn. The flashback cost is equal to its mana cost. (You may cast that card from your graveyard for its flashback cost. Then exile it.)', '/img/cards/snapcaster_mage.jpg', '{1}{U}', 2, 1),
    ('Jace, the Mind Sculptor', 'Planeswalker', 'Blue', 'Double Masters', 'Mythic', '+2: Look at the top card of target player''s library. You may put that card on the bottom of that player''s library. 0: Draw three cards, then put two cards from your hand on top of your library in any order. −1: Return target creature to its owner''s hand. −12: Exile all cards from target player''s library, then that player shuffles their hand into their library.', '/img/cards/jace_the_mind_sculptor.jpg', '{2}{U}{U}', NULL, 0),
    ('Cryptic Command', 'Instant', 'Blue', 'Iconic Masters', 'Rare', 'Choose two — • Counter target spell. • Return target permanent to its owner''s hand. • Tap all creatures your opponents control. • Draw a card.', '/img/cards/cryptic_command.jpg', '{1}{U}{U}{U}', NULL, 0),
    ('Daze', 'Instant', 'Blue', 'Eternal Masters', 'Uncommon', 'You may return an Island you control to its owner''s hand rather than pay this spell''s mana cost. Counter target spell unless its controller pays {1}.', '/img/cards/daze.jpg', '{1}{U}', NULL, 0),
    ('Ponder', 'Sorcery', 'Blue', 'Tarkir: Dragonstorm Commander', 'Common', 'Look at the top three cards of your library, then put them back in any order. You may shuffle. Draw a card.', '/img/cards/ponder.jpg', '{U}', NULL, 0),
    ('Delver of Secrets // Insectile Aberration', 'Creature', 'Gray', 'Innistrad Remastered', 'Common', 'dsdsdsds', '/img/cards/delver_of_secrets.jpg', '', NULL, 0),
    ('Mana Leak', 'Instant', 'Blue', 'Double Masters 2022', 'Common', 'Counter target spell unless its controller pays {3}.', '/img/cards/mana_leak.jpg', '{1}{U}', NULL, 0),
    ('Vendilion Clique', 'Creature', 'Blue', 'Masters 25', 'Mythic', 'Flash Flying When Vendilion Clique enters, look at target player''s hand. You may choose a nonland card from it. If you do, that player reveals the chosen card, puts it on the bottom of their library, then draws a card.', '/img/cards/vendilion_clique.jpg', '{1}{U}{U}', 3, 1),
    ('Dark Confidant', 'Creature', 'Black', 'Final Fantasy', 'Mythic', 'At the beginning of your upkeep, reveal the top card of your library and put that card into your hand. You lose life equal to its mana value.', '/img/cards/dark_confidant.jpg', '{1}{B}', 2, 1),
    ('Liliana of the Veil', 'Planeswalker', 'Black', 'Innistrad Remastered', 'Mythic', '+1: Each player discards a card. −2: Target player sacrifices a creature. −6: Separate all permanents target player controls into two piles. That player sacrifices all permanents in the pile of their choice.', '/img/cards/liliana_of_the_veil.jpg', '{1}{B}{B}', NULL, 0),
    ('Thoughtseize', 'Sorcery', 'Black', 'Double Masters', 'Rare', 'Target player reveals their hand. You choose a nonland card from it. That player discards that card. You lose 2 life.', '/img/cards/thoughtseize.jpg', '{B}', NULL, 0),
    ('Damnation', 'Sorcery', 'Black', 'Double Masters 2022', 'Rare', 'Destroy all creatures. They can''t be regenerated.', '/img/cards/damnation.jpg', '{2}{B}{B}', NULL, 0),
    ('Snuff Out', 'Instant', 'Black', 'Duel Decks Anthology: Garruk vs. Liliana', 'Common', 'If you control a Swamp, you may pay 4 life rather than pay this spell''s mana cost. Destroy target nonblack creature. It can''t be regenerated.', '/img/cards/snuff_out.jpg', '{3}{B}', NULL, 0),
    ('Cabal Coffers', 'Land', 'Gray', 'Modern Horizons 2', 'Mythic', '{2}, {T}: Add {B} for each Swamp you control.', '/img/cards/cabal_coffers.jpg', '', NULL, 0),
    ('Dark Ritual', 'Instant', 'Black', 'Masters 25', 'Common', 'Add {B}{B}{B}.', '/img/cards/dark_ritual.jpg', '{B}', NULL, 0),
    ('Reanimate', 'Sorcery', 'Black', 'Duskmourn: House of Horror Commander', 'Rare', 'Put target creature card from a graveyard onto the battlefield under your control. You lose life equal to that card''s mana value.', '/img/cards/reanimate.jpg', '{B}', NULL, 0),
    ('Bone Shards', 'Sorcery', 'Black', 'Modern Horizons 2', 'Common', 'As an additional cost to cast this spell, sacrifice a creature or discard a card. Destroy target creature or planeswalker.', '/img/cards/bone_shards.jpg', '{B}', NULL, 0),
    ('Bloodghast', 'Creature', 'Black', 'Secrets of Strixhaven Commander', 'Rare', 'This creature can''t block. This creature has haste as long as an opponent has 10 or less life. Landfall — Whenever a land you control enters, you may return this card from your graveyard to the battlefield.', '/img/cards/bloodghast.jpg', '{B}{B}', 2, 1),
    ('Tasigur, the Golden Fang', 'Creature', 'Black', 'Tarkir: Dragonstorm Commander', 'Rare', 'Delve (Each card you exile from your graveyard while casting this spell pays for {1}.) {2}{G/U}{G/U}: Mill two cards, then return a nonland card of an opponent''s choice from your graveyard to your hand.', '/img/cards/tasigur_the_golden_fang.jpg', '{5}{B}', 4, 5),
    ('Lightning Bolt', 'Instant', 'Red', 'Ravnica: Clue Edition', 'Uncommon', 'Lightning Bolt deals 3 damage to any target.', '/img/cards/lightning_bolt.jpg', '{R}', NULL, 0),
    ('Goblin Welder', 'Creature', 'Red', 'Commander Anthology Volume II', 'Rare', '{T}: Choose target artifact a player controls and target artifact card in that player''s graveyard. If both targets are still legal as this ability resolves, that player simultaneously sacrifices the artifact and returns the artifact card to the battlefield.', '/img/cards/goblin_welder.jpg', '{R}', 1, 1),
    ('Eidolon of the Great Revel', 'Creature', 'Red', 'Masters 25', 'Rare', 'Whenever a player casts a spell with mana value 3 or less, this creature deals 2 damage to that player.', '/img/cards/eidolon_of_the_great_revel.jpg', '{R}{R}', 2, 2),
    ('Monastery Swiftspear', 'Creature', 'Red', 'The Brothers'' War', 'Uncommon', 'Haste Prowess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)', '/img/cards/monastery_swiftspear.jpg', '{R}', 1, 2),
    ('Rift Bolt', 'Sorcery', 'Red', 'Double Masters 2022', 'Common', 'Rift Bolt deals 3 damage to any target. Suspend 1—{R} (Rather than cast this card from your hand, you may pay {R} and exile it with a time counter on it. At the beginning of your upkeep, remove a time counter. When the last is removed, you may cast it without paying its mana cost.)', '/img/cards/rift_bolt.jpg', '{2}{R}', NULL, 0),
    ('Chandra, Torch of Defiance', 'Planeswalker', 'Red', 'Reality Fracture', 'Mythic', '+1: Exile the top card of your library. You may cast that card. If you don''t, Chandra deals 2 damage to each opponent. +1: Add {R}{R}. −3: Chandra deals 4 damage to target creature. −7: You get an emblem with "Whenever you cast a spell, this emblem deals 5 damage to any target."', '/img/cards/chandra_torch_of_defiance.jpg', '{2}{R}{R}', NULL, 0),
    ('Skullcrack', 'Instant', 'Red', 'Ravnica Remastered', 'Uncommon', 'Players can''t gain life this turn. Damage can''t be prevented this turn. Skullcrack deals 3 damage to target player or planeswalker.', '/img/cards/skullcrack.jpg', '{1}{R}', NULL, 0),
    ('Searing Blaze', 'Instant', 'Red', 'Duel Decks: Venser vs. Koth', 'Common', 'Searing Blaze deals 1 damage to target player or planeswalker and 1 damage to target creature that player or that planeswalker''s controller controls. Landfall — If you had a land enter the battlefield under your control this turn, Searing Blaze deals 3 damage to that player or planeswalker and 3 damage to that creature instead.', '/img/cards/searing_blaze.jpg', '{R}{R}', NULL, 0),
    ('Goblin Lackey', 'Creature', 'Red', 'Vintage Masters', 'Rare', 'Whenever this creature deals damage to a player, you may put a Goblin permanent card from your hand onto the battlefield.', '/img/cards/goblin_lackey.jpg', '{R}', 1, 1),
    ('Sulfuric Vortex', 'Enchantment', 'Red', 'Dominaria Remastered', 'Rare', 'At the beginning of each player''s upkeep, this enchantment deals 2 damage to that player. If a player would gain life, that player gains no life instead.', '/img/cards/sulfuric_vortex.jpg', '{1}{R}{R}', NULL, 0),
    ('Llanowar Elves', 'Creature', 'Green', 'Foundations', 'Common', '{T}: Add {G}.', '/img/cards/llanowar_elves.jpg', '{G}', 1, 1),
    ('Birds of Paradise', 'Creature', 'Green', 'Ravnica Remastered', 'Rare', 'Flying {T}: Add one mana of any color.', '/img/cards/birds_of_paradise.jpg', '{G}', 0, 1),
    ('Tarmogoyf', 'Creature', 'Green', 'Time Spiral Remastered', 'Mythic', 'Tarmogoyf''s power is equal to the number of card types among cards in all graveyards and its toughness is equal to that number plus 1.', '/img/cards/tarmogoyf.jpg', '{1}{G}', NULL, 0),
    ('Noble Hierarch', 'Creature', 'Green', 'Double Masters', 'Rare', 'Exalted (Whenever a creature you control attacks alone, that creature gets +1/+1 until end of turn.) {T}: Add {G}, {W}, or {U}.', '/img/cards/noble_hierarch.jpg', '{G}', 0, 1),
    ('Eternal Witness', 'Creature', 'Green', 'Commander Masters', 'Uncommon', 'When this creature enters, you may return target card from your graveyard to your hand.', '/img/cards/eternal_witness.jpg', '{1}{G}{G}', 2, 1),
    ('Garruk Wildspeaker', 'Planeswalker', 'Green', 'Commander 2011', 'Mythic', '+1: Untap two target lands. −1: Create a 3/3 green Beast creature token. −4: Creatures you control get +3/+3 and gain trample until end of turn.', '/img/cards/garruk_wildspeaker.jpg', '{2}{G}{G}', NULL, 0),
    ('Scavenging Ooze', 'Creature', 'Green', 'Foundations', 'Rare', '{G}: Exile target card from a graveyard. If it was a creature card, put a +1/+1 counter on this creature and you gain 1 life.', '/img/cards/scavenging_ooze.jpg', '{1}{G}', 2, 2),
    ('Collected Company', 'Instant', 'Green', 'Dragons of Tarkir', 'Rare', 'Look at the top six cards of your library. Put up to two creature cards with mana value 3 or less from among them onto the battlefield. Put the rest on the bottom of your library in any order.', '/img/cards/collected_company.jpg', '{3}{G}', NULL, 0),
    ('Worldly Tutor', 'Instant', 'Green', 'Dominaria Remastered', 'Rare', 'Search your library for a creature card, reveal it, then shuffle and put the card on top.', '/img/cards/worldly_tutor.jpg', '{G}', NULL, 0),
    ('Wild Nacatl', 'Creature', 'Green', 'Duel Decks: Ajani vs. Nicol Bolas', 'Common', 'This creature gets +1/+1 as long as you control a Mountain. This creature gets +1/+1 as long as you control a Plains.', '/img/cards/wild_nacatl.jpg', '{G}', 1, 1),
    ('Courser of Kruphix', 'Creature', 'Green', 'Commander Masters', 'Rare', 'Play with the top card of your library revealed. You may play lands from the top of your library. Landfall — Whenever a land you control enters, you gain 1 life.', '/img/cards/courser_of_kruphix.jpg', '{1}{G}{G}', 2, 4),
    ('Lightning Helix', 'Instant', 'Red,White', 'Murders at Karlov Manor', 'Uncommon', 'Lightning Helix deals 3 damage to any target and you gain 3 life.', '/img/cards/lightning_helix.jpg', '{R}{W}', NULL, 0),
    ('Maelstrom Pulse', 'Sorcery', 'Black,Green', 'Innistrad Remastered', 'Rare', 'Destroy target nonland permanent and all other permanents with the same name as that permanent.', '/img/cards/maelstrom_pulse.jpg', '{1}{B}{G}', NULL, 0),
    ('Sphinx''s Revelation', 'Instant', 'Blue,White', 'The List', 'Rare', 'You gain X life and draw X cards.', '/img/cards/sphinxs_revelation.jpg', '{X}{W}{U}{U}', NULL, 0),
    ('Voice of Resurgence', 'Creature', 'Green,White', 'Double Masters', 'Rare', 'Whenever an opponent casts a spell during your turn and when this creature dies, create a green and white Elemental creature token with "This token''s power and toughness are each equal to the number of creatures you control."', '/img/cards/voice_of_resurgence.jpg', '{G}{W}', 2, 2),
    ('Geist of Saint Traft', 'Legendary_Creature', 'Blue,White', 'Crimson Vow Commander', 'Mythic', 'Hexproof (This creature can''t be the target of spells or abilities your opponents control.) Whenever Geist of Saint Traft attacks, create a 4/4 white Angel creature token with flying that''s tapped and attacking. Exile that token at end of combat.', '/img/cards/geist_of_saint_traft.jpg', '{1}{W}{U}', 2, 2),
    ('Bloodbraid Elf', 'Creature', 'Green,Red', 'Double Masters 2022', 'Uncommon', 'Haste (This creature can attack and {T} as soon as it comes under your control.) Cascade (When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom in a random order.)', '/img/cards/bloodbraid_elf.jpg', '{2}{R}{G}', 3, 2),
    ('Kitchen Finks', 'Creature', 'Green,White', 'Ultimate Masters', 'Uncommon', 'When this creature enters, you gain 2 life. Persist (When this creature dies, if it had no -1/-1 counters on it, return it to the battlefield under its owner''s control with a -1/-1 counter on it.)', '/img/cards/kitchen_finks.jpg', '{1}{G/W}{G/W}', 3, 2),
    ('Notion Thief', 'Creature', 'Black,Blue', 'Zendikar Rising Commander', 'Rare', 'Flash If an opponent would draw a card except the first one they draw in each of their draw steps, instead that player skips that draw and you draw a card.', '/img/cards/notion_thief.jpg', '{2}{U}{B}', 3, 1),
    ('Anguished Unmaking', 'Instant', 'Black,White', 'Secrets of Strixhaven Commander', 'Rare', 'Exile target nonland permanent. You lose 3 life.', '/img/cards/anguished_unmaking.jpg', '{1}{W}{B}', NULL, 0),
    ('Sol Ring', 'Artifact', 'Gray', 'Secrets of Strixhaven Commander', 'Uncommon', '{T}: Add {C}{C}.', '/img/cards/sol_ring.jpg', '{1}', NULL, 0),
    ('Mana Crypt', 'Artifact', 'Gray', 'Double Masters', 'Mythic', 'At the beginning of your upkeep, flip a coin. If you lose the flip, this artifact deals 3 damage to you. {T}: Add {C}{C}.', '/img/cards/mana_crypt.jpg', '{0}', NULL, 0),
    ('Sensei''s Divining Top', 'Artifact', 'Gray', 'Double Masters 2022', 'Rare', '{1}: Look at the top three cards of your library, then put them back in any order. {T}: Draw a card, then put this artifact on top of its owner''s library.', '/img/cards/senseis_divining_top.jpg', '{1}', NULL, 0),
    ('Aether Vial', 'Artifact', 'Gray', 'Double Masters 2022', 'Rare', 'At the beginning of your upkeep, you may put a charge counter on this artifact. {T}: You may put a creature card with mana value equal to the number of charge counters on this artifact from your hand onto the battlefield.', '/img/cards/aether_vial.jpg', '{1}', NULL, 0),
    ('Umezawa''s Jitte', 'Artifact', 'Gray', 'Betrayers of Kamigawa', 'Rare', 'Whenever equipped creature deals combat damage, put two charge counters on Umezawa''s Jitte. Remove a charge counter from Umezawa''s Jitte: Choose one — • Equipped creature gets +2/+2 until end of turn. • Target creature gets -1/-1 until end of turn. • You gain 2 life. Equip {2}', '/img/cards/umezawas_jitte.jpg', '{2}', NULL, 0),
    ('Wurmcoil Engine', 'Creature', 'Gray', 'Double Masters', 'Mythic', 'Deathtouch, lifelink When this creature dies, create a 3/3 colorless Phyrexian Wurm artifact creature token with deathtouch and a 3/3 colorless Phyrexian Wurm artifact creature token with lifelink.', '/img/cards/wurmcoil_engine.jpg', '{6}', 6, 6),
    ('Wasteland', 'Land', 'Gray', 'Eternal Masters', 'Rare', '{T}: Add {C}. {T}, Sacrifice this land: Destroy target nonbasic land.', '/img/cards/wasteland.jpg', '', NULL, 0),
    ('Polluted Delta', 'Land', 'Gray', 'Modern Horizons 3', 'Rare', '{T}, Pay 1 life, Sacrifice this land: Search your library for an Island or Swamp card, put it onto the battlefield, then shuffle.', '/img/cards/polluted_delta.jpg', '', NULL, 0),
    ('Flooded Strand', 'Land', 'Gray', 'Modern Horizons 3', 'Rare', '{T}, Pay 1 life, Sacrifice this land: Search your library for a Plains or Island card, put it onto the battlefield, then shuffle.', '/img/cards/flooded_strand.jpg', '', NULL, 0),
    ('Volcanic Island', 'Land', 'Gray', 'Vintage Masters', 'Rare', '({T}: Add {U} or {R}.)', '/img/cards/volcanic_island.jpg', '', NULL, 0),
    ('Tropical Island', 'Land', 'Gray', 'Vintage Masters', 'Rare', '({T}: Add {G} or {U}.)', '/img/cards/tropical_island.jpg', '', NULL, 0),
    ('Tundra', 'Land', 'Gray', 'Vintage Masters', 'Rare', '({T}: Add {W} or {U}.)', '/img/cards/tundra.jpg', '', NULL, 0);

-- --------------------------------------------------------
-- Credentials
-- All 5 users have password: Password123!
-- --------------------------------------------------------
INSERT INTO Credentials (Email, PasswordHash, UserRole) VALUES
    ('admin@deckforge.com',   '$2b$12$vZMB9D7V3Fj79eOD1ej36OVU6HkidCd4KQ7s1RYRW3tRhXI4JV89O', 'ADMIN'),
    ('alice@example.com',     '$2b$12$ALiUpGsWhpn7A8GaCp0UVO2yI/cQE/hNq8jJnkRkv7s2BzCbKXEOq', 'MEMBER'),
    ('bob@example.com',       '$2b$12$0Br4CUiL.Rhn5WUyuPqAhel0L6w9GZ5sKpW1z3C2B63uZttSzubka', 'MEMBER'),
    ('carol@example.com',     '$2b$12$5Gsn39ZeWDNf/Dck.i3UK.77jb50SIbqaBLKOb0Lw8Co/MKu0qs3O', 'MEMBER'),
    ('dave@example.com',      '$2b$12$Nrnlo.cUSVq8k9sb0QaJ9.FXlm3dtwrbIFje49nmgKQXnZYJ/Pso.', 'MEMBER');

-- --------------------------------------------------------
-- Users
-- --------------------------------------------------------
INSERT INTO Users (Name, Age, UserCredentialsId) VALUES
    ('Admin Account', '1995-02-01', 1),
    ('Alice Johnson', '2000-07-12', 2),
    ('Bob Smith',     '1990-06-07', 3),
    ('Carol White',   '1989-05-07', 4),
    ('Dave Brown',    '2010-07-08', 5);

-- --------------------------------------------------------
-- Collections
-- --------------------------------------------------------
INSERT INTO Collections (UserId,CardId) VALUES
    (2, 1),    -- Alice
    (3, 2),   -- Bob
    (4, 3),   -- Carol
    (5, 4);    -- Dave
